manifest_path: ./manifest.json
num_workers: 4
limit: null
resume: false
recover_in_progress: true
show_progress: true
path_mapping:
  local_mount: /home/
  oss_prefix: oss://
ray:
  address: null
  init:
    ignore_reinit_error: true
  worker:
    num_cpus: 1
    num_gpus: 0
    resources: {}
